---
title: "Practice Activity 2.1: Titanic Wrangling"
author: "Sydney Thompson"
format: html
---

# Titanic Wrangling

In this practice activity you'll continue to work with the titanic dataset in ways that flex what you've learned about both data wrangling and data visualization.

# Import the titanic dataset here

```{python}
import pandas as pd
import numpy as np

data_dir = "https://dlsun.github.io/pods/data/"
df_titanic = pd.read_csv(data_dir + "titanic.csv")
df_titanic.head()
```

## 1. Filter the data to include passengers only. Calculate the joint distribution (cross-tab) between a passenger's class and where they embarked.
# code here

```{python}
df_titanic["name"]
```


```{python}
# code here

df_passengers = df_titanic.loc[(df_titanic["class"] == "1st") | (df_titanic["class"] == "2nd") | (df_titanic["class"] == "3rd")]
df_passengers
pd.crosstab(df_passengers["class"], df_passengers["embarked"])

```

## 2. Using the joint distribution that calculated above, calculate the following:

* the conditional distribution of their class given where they embarked
* the conditional distribution of where they embarked given their class

Use the conditional distributions that you calculate to answer the following quesitons:

* What proportion of 3rd class passengers embarked at Southampton?
* What proportion of Southampton passengers were in 3rd class?

```{python}
# Code here

# The conditional distribution of class given where they embarked
conditional_class_given_embarked = pd.crosstab(df_titanic["class"], df_titanic["embarked"], normalize="columns")
conditional_class_given_embarked
```

```{python}
# What proportion of Southampton passengers were in 3rd class?

# Proportion of Southampton passengers who were in 3rd class
proportion_southampton_3rd = conditional_class_given_embarked.loc["3rd", "S"]
proportion_southampton_3rd
```

```{python}

conditional_embarked_given_class = pd.crosstab(df_titanic["class"], df_titanic["embarked"], normalize="index")
conditional_embarked_given_class

```

```{python}
# what is the proportion of third class passengers who embarked at Southampton?

# Proportion of 3rd class passengers who embarked at Southampton
proportion_3rd_southampton = conditional_embarked_given_class.loc["3rd", "S"]
proportion_3rd_southampton
```

## 3. Make a visualization showing the distribution of a passenger's class, given where they embarked.

Discuss the pros and cons of using this visualization versus the distributions you calculated before, to answer the previous questions.

```{python}
# Code here

import plotnine as p9
from plotnine import *
import pandas as pd

ggplot(df_passengers, aes(x="class", fill="embarked")) + geom_bar(position="dodge")

```

I think this visualization is good at comparing the different classes of individuals because they are side-by-side. We're able to see that the majority of passengers embarked from Southampton. The crosstab plots above are better at showing the proportion of passengers and calculating probabilities.